name: Net.gigaclub.OnlyJoinOnLivestreamMCSpigot1.10
version: 1.0-SNAPSHOT
main: net.gigaclub.onlyjoinonlivestreammcspigot.Main
authors: [GigaClub]
website: https://GigaClub.net
commands:
  addViewer:
    description: addViewer
    permission: OJL.addViewer
  showViewer:
    description: showViewer
    permission: OJL.showViewer
  remViewer:
    description: remViewer
    permission: OJL.remViewer
permissions:
  OJL.addViewer:
    default: op
  OJL.showViewer:
    default: op
  OJL.remViewer:
    default: op