name: Net.gigaclub.OnlyJoinOnLivestreamMCSpigot1.10
version: 1.0-SNAPSHOT
main: net.gigaclub.onlyjoinonlivestreammcspigot.Main
authors: [GigaClub]
website: https://GigaClub.net
commands:
  addViewer:
    description: addViewer
    permission: OJL.addViewer
  showViewer:
    description: showViewer
    permission: OJL.showViewer
  remViewer:
    description: remViewer
    permission: OJL.remViewer
  addStreamer:
    description: addStreamer
    permission: OJL.addStreamer
  showStreamer:
    description: showStreamer
    permission: OJL.showStreamer
  remStreamer:
    description: remStreamer
    permission: OJL.remStreamer
permissions:
  OJL.addViewer:
    default: op
  OJL.showViewer:
    default: op
  OJL.remViewer:
    default: op
  OJL.addStreamer:
    default: op
  OJL.showStreamer:
    default: op
  OJL.remStreamer:
    default: op